{{- $root := . -}}
{{- if index .Values "postgresql-ha" "initDbScriptSecret" "enabled" }}
---
apiVersion: v1
metadata:
  labels:
    app.kuberentes.io/name: {{ include "openwifi.name" . }}
    helm.sh/chart: {{ include "openwifi.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "openwifi.fullname" . }}-initdb-scripts
kind: Secret
type: Opaque
data:
  users_creation.sh: {{ include "openwifi.user_creation_script" . | b64enc | quote }}
{{- end }}
