{{- $root := . -}}
{{- if .Values.clustersysteminfo.enabled }}
{{- range $image, $imageValue := .Values.clustersysteminfo.images }}
{{- if $imageValue.regcred }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  labels:
    app.kuberentes.io/name: {{ include "openwifi.name" $root }}
    helm.sh/chart: {{ include "openwifi.chart" $root }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    app.kubernetes.io/managed-by: {{ $root.Release.Service }}
  name: {{ include "openwifi.fullname" $root }}-{{ $image }}-clustersysteminfo-regcred
data:
  .dockerconfigjson: {{ $imageValue.regcred | quote }}
{{- end }}
{{- end }}
{{- end }}
