{{- $root := . -}}
{{- if .Values.clustersysteminfo.enabled }}
---
apiVersion: v1
metadata:
  labels:
    app.kuberentes.io/name: {{ include "openwifi.name" . }}
    helm.sh/chart: {{ include "openwifi.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "openwifi.fullname" . }}-clustersysteminfo-env
kind: Secret
type: Opaque
data:
  # Secret env variables
  {{- range $key, $value := .Values.clustersysteminfo.secret_env_variables }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
